'use client'

import { cn } from '@/lib/utils'
import { NarrativeStatement } from '@/components/why-movemental/NarrativeStatement'
import { RevenueFlowChart } from '../visualizations/RevenueFlowChart'
import { alanLaunchConfig } from '../data/valuation-data'
import { Book, Bot, FileText, GraduationCap, Globe } from 'lucide-react'

interface RevenueFlowProps {
  className?: string
}

const assetIcons: Record<string, React.ReactNode> = {
  Books: <Book className="h-4 w-4" />,
  'AI Companion': <Bot className="h-4 w-4" />,
  Articles: <FileText className="h-4 w-4" />,
  Courses: <GraduationCap className="h-4 w-4" />,
}

export function RevenueFlow({ className }: RevenueFlowProps) {
  return (
    <div className={cn('space-y-16', className)}>
      <NarrativeStatement alignment="center">
        Revenue flows through <strong>two streams.</strong>
      </NarrativeStatement>

      {/* Two Streams Explanation */}
      <div className="grid md:grid-cols-2 gap-6 max-w-3xl mx-auto">
        <div className="p-6 rounded-xl border bg-blue-50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-800">
          <h4 className="font-semibold text-blue-700 dark:text-blue-400 mb-2">
            Creator Revenue (GMV)
          </h4>
          <p className="text-sm text-muted-foreground">
            Total revenue generated by creators through their platform—book sales, courses,
            subscriptions, consulting. This is <em>their</em> money.
          </p>
        </div>
        <div className="p-6 rounded-xl border bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-800">
          <h4 className="font-semibold text-emerald-700 dark:text-emerald-400 mb-2">
            Movemental Earnings
          </h4>
          <p className="text-sm text-muted-foreground">
            One-time platform fee ($1k–$4k) plus 10% of ongoing platform revenue.
            This is what we actually earn.
          </p>
        </div>
      </div>

      {/* Case Study: Alan */}
      <div className="space-y-8">
        <div className="text-center">
          <h3 className="text-2xl font-bold mb-2">Case Study: {alanLaunchConfig.name}</h3>
          <p className="text-muted-foreground">{alanLaunchConfig.role}</p>
        </div>

        {/* What Alan Launches With */}
        <div className="max-w-3xl mx-auto p-6 rounded-xl bg-muted/30 border">
          <h4 className="font-semibold mb-4">Launch Configuration</h4>

          <div className="grid sm:grid-cols-2 gap-4 mb-6">
            {alanLaunchConfig.assets.map((asset) => (
              <div key={asset.type} className="flex items-start gap-3 text-sm">
                <div className="p-1.5 rounded bg-primary/10 text-primary shrink-0">
                  {assetIcons[asset.type] || <FileText className="h-4 w-4" />}
                </div>
                <div>
                  <p className="font-medium">{asset.type}</p>
                  <p className="text-muted-foreground text-xs">{asset.description}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="pt-4 border-t">
            <div className="flex items-center gap-2 mb-2">
              <Globe className="h-4 w-4 text-primary" />
              <span className="font-medium text-sm">Launch Languages</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {alanLaunchConfig.languages.map((lang) => (
                <span
                  key={lang}
                  className="px-3 py-1 rounded-full bg-primary/10 text-primary text-sm"
                >
                  {lang}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Revenue Projections Chart */}
        <div className="max-w-3xl mx-auto">
          <h4 className="text-lg font-semibold mb-4 text-center">
            Projected Revenue by Language
          </h4>
          <RevenueFlowChart />
        </div>
      </div>
    </div>
  )
}
