import json
import os
import re
from pathlib import Path

manuscript_dir = Path(__file__).parent.parent / '_docs' / 'book-development' / 'manuscript-final'

files = [
    '00-preface-the-story.md',
    '01-chapter-01-the-credibility-collapse.md',
    '02-chapter-02-ai-as-both-problem-and-solution.md',
    '03-chapter-03-why-movement-leaders-were-right-to-ignore-seo.md',
    '04-chapter-04-where-we-are.md',
    '05-chapter-05-finding-a-guide.md',
    '06-chapter-06-ai-as-amplification.md',
    '07-chapter-07-voice-preservation.md',
    '08-chapter-08-scenius-as-credibility-solution.md',
    '09-chapter-09-transparency-disclosure-and-trust.md',
    '10-chapter-10-theological-integrity.md',
    '11-chapter-11-agents-as-assistants.md',
    '12-chapter-12-the-70-30-rule.md',
    '13-chapter-13-spectrum-and-domains.md',
    '14-chapter-14-personalization-and-context.md',
    '15-chapter-15-what-churches-must-refuse.md',
    '16-chapter-16-what-they-are-ethically-free-to-do.md',
    '17-chapter-17-why-embodied-leadership-cannot-be-automated.md',
    '18-chapter-18-from-gutenberg-to-networks.md',
    '19-chapter-19-content-that-moves.md',
]

parts = [
    {'number': 1, 'title': "The Crisis We're In", 'chapters': [1, 2, 3, 4, 5]},
    {'number': 2, 'title': 'The Framework', 'chapters': [6, 7, 8, 9, 10]},
    {'number': 3, 'title': 'The Practice', 'chapters': [11, 12, 13]},
    {'number': 4, 'title': 'The Boundaries', 'chapters': [14, 15, 16, 17]},
    {'number': 5, 'title': 'The Long Arc', 'chapters': [18, 19]},
]

def extract_title(content):
    import re
    match = re.match(r'^# (?:Preface|Chapter \d+): (.+)$', content, re.MULTILINE)
    return match.group(1) if match else ''

def extract_description(content):
    lines = content.split('\n')
    found_title = False
    for line in lines:
        if re.match(r'^# (?:Preface|Chapter \d+):', line):
            found_title = True
            continue
        if found_title and line.strip() and not re.match(r'^##', line):
            desc = line.strip()
            return desc[:147] + '...' if len(desc) > 150 else desc
    return 'A chapter from The Movemental AI Book.'

def calculate_reading_time(content):
    return (len(content.split()) + 224) // 225

def create_slug(title):
    import re
    return re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')

chapters = []
chapter_number = 0

for index, file in enumerate(files):
    file_path = manuscript_dir / file
    content = file_path.read_text(encoding='utf-8')
    
    # Remove the markdown header
    content_without_header = re.sub(r'^# (?:Preface|Chapter \d+): .+\n\n', '', content, flags=re.MULTILINE)
    
    title = extract_title(content)
    description = extract_description(content)
    reading_time = calculate_reading_time(content)
    
    if index == 0:
        chapters.append({
            'id': 'preface',
            'number': 0,
            'title': 'Preface: The Story',
            'slug': 'preface-the-story',
            'partNumber': 0,
            'partTitle': 'Preface',
            'description': description,
            'readingTime': reading_time,
            'content': content_without_header.strip(),
        })
    else:
        chapter_number += 1
        part = next(p for p in parts if chapter_number in p['chapters'])
        
        chapters.append({
            'id': f'chapter-{chapter_number:02d}',
            'number': chapter_number,
            'title': title,
            'slug': create_slug(title),
            'partNumber': part['number'],
            'partTitle': part['title'],
            'description': description,
            'readingTime': reading_time,
            'content': content_without_header.strip(),
        })

# Generate TypeScript file
output_lines = ['''/**
 * AI Book Chapter Data
 * 
 * This file contains all chapter metadata and content for the Movemental AI Book.
 * The book follows a five-part structure: Crisis → Framework → Practice → Boundaries → Long Arc
 * 
 * Content sourced from: _docs/book-development/manuscript-final/
 * Generated by: scripts/build-book-data.py
 */

export interface BookChapter {
  id: string
  number: number
  title: string
  slug: string
  partNumber: number
  partTitle: string
  description: string
  readingTime: number
  content: string
}

export interface BookPart {
  number: number
  title: string
  description: string
  chapters: BookChapter[]
}

// Preface
export const PREFACE: BookChapter = {
  id: 'preface',
  number: 0,
  title: 'Preface: The Story',
  slug: 'preface-the-story',
  partNumber: 0,
  partTitle: 'Preface',
  description: ''' + json.dumps(chapters[0]['description']) + ''',
  readingTime: ''' + str(chapters[0]['readingTime']) + ''',
  content: ''' + json.dumps(chapters[0]['content']) + ''',
};

// Part I: The Crisis We're In
const PART_1_CHAPTERS: BookChapter[] = [
''']

for ch in chapters[1:6]:
    output_lines.append(f'''  {{
    id: {json.dumps(ch['id'])},
    number: {ch['number']},
    title: {json.dumps(ch['title'])},
    slug: {json.dumps(ch['slug'])},
    partNumber: {ch['partNumber']},
    partTitle: {json.dumps(ch['partTitle'])},
    description: {json.dumps(ch['description'])},
    readingTime: {ch['readingTime']},
    content: {json.dumps(ch['content'])},
  }},''')

output_lines.append('''];

// Part II: The Framework
const PART_2_CHAPTERS: BookChapter[] = [
''')

for ch in chapters[6:11]:
    output_lines.append(f'''  {{
    id: {json.dumps(ch['id'])},
    number: {ch['number']},
    title: {json.dumps(ch['title'])},
    slug: {json.dumps(ch['slug'])},
    partNumber: {ch['partNumber']},
    partTitle: {json.dumps(ch['partTitle'])},
    description: {json.dumps(ch['description'])},
    readingTime: {ch['readingTime']},
    content: {json.dumps(ch['content'])},
  }},''')

output_lines.append('''];

// Part III: The Practice
const PART_3_CHAPTERS: BookChapter[] = [
''')

for ch in chapters[11:14]:
    output_lines.append(f'''  {{
    id: {json.dumps(ch['id'])},
    number: {ch['number']},
    title: {json.dumps(ch['title'])},
    slug: {json.dumps(ch['slug'])},
    partNumber: {ch['partNumber']},
    partTitle: {json.dumps(ch['partTitle'])},
    description: {json.dumps(ch['description'])},
    readingTime: {ch['readingTime']},
    content: {json.dumps(ch['content'])},
  }},''')

output_lines.append('''];

// Part IV: The Boundaries
const PART_4_CHAPTERS: BookChapter[] = [
''')

for ch in chapters[14:18]:
    output_lines.append(f'''  {{
    id: {json.dumps(ch['id'])},
    number: {ch['number']},
    title: {json.dumps(ch['title'])},
    slug: {json.dumps(ch['slug'])},
    partNumber: {ch['partNumber']},
    partTitle: {json.dumps(ch['partTitle'])},
    description: {json.dumps(ch['description'])},
    readingTime: {ch['readingTime']},
    content: {json.dumps(ch['content'])},
  }},''')

output_lines.append('''];

// Part V: The Long Arc
const PART_5_CHAPTERS: BookChapter[] = [
''')

for ch in chapters[18:20]:
    output_lines.append(f'''  {{
    id: {json.dumps(ch['id'])},
    number: {ch['number']},
    title: {json.dumps(ch['title'])},
    slug: {json.dumps(ch['slug'])},
    partNumber: {ch['partNumber']},
    partTitle: {json.dumps(ch['partTitle'])},
    description: {json.dumps(ch['description'])},
    readingTime: {ch['readingTime']},
    content: {json.dumps(ch['content'])},
  }},''')

output_lines.append('''];

// Combine all chapters (excluding preface from main list, but available separately)
export const ALL_CHAPTERS: BookChapter[] = [
  ...PART_1_CHAPTERS,
  ...PART_2_CHAPTERS,
  ...PART_3_CHAPTERS,
  ...PART_4_CHAPTERS,
  ...PART_5_CHAPTERS,
]

// Book parts structure
export const BOOK_PARTS: BookPart[] = [
  {
    number: 1,
    title: 'The Crisis We\\'re In',
    description: 'Understanding the credibility collapse in an AI-saturated world.',
    chapters: PART_1_CHAPTERS,
  },
  {
    number: 2,
    title: 'The Framework',
    description: 'Principles for navigating AI as a movement leader.',
    chapters: PART_2_CHAPTERS,
  },
  {
    number: 3,
    title: 'The Practice',
    description: 'Practical approaches for using AI well.',
    chapters: PART_3_CHAPTERS,
  },
  {
    number: 4,
    title: 'The Boundaries',
    description: 'What to embrace and what to refuse.',
    chapters: PART_4_CHAPTERS,
  },
  {
    number: 5,
    title: 'The Long Arc',
    description: 'The future of credibility and content that moves.',
    chapters: PART_5_CHAPTERS,
  },
]

// Book metadata
export const BOOK_METADATA = {
  title: 'The Movemental AI Book',
  subtitle: 'Navigating Credibility, AI, and Movement Leadership',
  description: 'A comprehensive guide for movement leaders navigating the AI age—preserving voice, building credibility through networks, and creating content that transforms.',
  totalChapters: ALL_CHAPTERS.length,
  totalReadingTime: ALL_CHAPTERS.reduce((sum, ch) => sum + ch.readingTime, 0),
  author: 'Movemental',
}

// Helper functions
export function getChapterById(id: string): BookChapter | undefined {
  return ALL_CHAPTERS.find(ch => ch.id === id) || (id === 'preface' ? PREFACE : undefined)
}

export function getChapterBySlug(slug: string): BookChapter | undefined {
  return ALL_CHAPTERS.find(ch => ch.slug === slug) || (slug === 'preface-the-story' ? PREFACE : undefined)
}

export function getChapterByNumber(number: number): BookChapter | undefined {
  if (number === 0) return PREFACE;
  return ALL_CHAPTERS.find(ch => ch.number === number)
}

export function getAdjacentChapters(currentNumber: number): { prev?: BookChapter; next?: BookChapter } {
  if (currentNumber === 0) {
    return { prev: undefined, next: ALL_CHAPTERS[0] };
  }
  const currentIndex = ALL_CHAPTERS.findIndex(ch => ch.number === currentNumber)
  return {
    prev: currentIndex > 0 ? ALL_CHAPTERS[currentIndex - 1] : (currentNumber === 1 ? PREFACE : undefined),
    next: currentIndex < ALL_CHAPTERS.length - 1 ? ALL_CHAPTERS[currentIndex + 1] : undefined,
  }
}

export function getPartForChapter(chapterNumber: number): BookPart | undefined {
  if (chapterNumber === 0) return undefined;
  return BOOK_PARTS.find(part => 
    part.chapters.some(ch => ch.number === chapterNumber)
  )
}
''')

output_path = Path(__file__).parent.parent / 'lib' / 'data' / 'ai-book-chapters.ts'
output_path.write_text(''.join(output_lines), encoding='utf-8')
print(f'Book data file generated successfully at {output_path}!')
