#!/usr/bin/env python3
"""Build lean movement-leader substrate from alan-hirsch source files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs/movement_leader_research/alan-hirsch"
OUT = SRC / "ALAN_HIRSCH_RESEARCH_COLLATED.md"


def read(name: str) -> str:
    return (SRC / name).read_text(encoding="utf-8")


def extract_books_table(md: str) -> list[dict]:
    """Parse books.md into rows (newest-first order preserved in file)."""
    books: list[dict] = []
    blocks = re.split(r"\n---\n", md)
    for block in blocks:
        if "### " not in block or "| Field |" not in block:
            continue
        title_m = re.search(r"^### (.+)$", block, re.M)
        if not title_m:
            continue
        title = title_m.group(1).strip()
        if title.startswith("Books ") or title in ("Forthcoming", "Bibliography Summary"):
            continue

        def field(name: str) -> str:
            m = re.search(rf"\| {re.escape(name)} \| ([^\|]+) \|", block)
            return m.group(1).strip() if m else ""

        authors = field("Author(s)")
        publisher = field("Publisher")
        published = field("Published")
        isbn = field("ISBN-13")
        themes = field("Key Themes")
        desc_m = re.search(r"\*\*Description\*\*: (.+)", block)
        desc = desc_m.group(1).strip() if desc_m else ""
        if len(desc) > 200:
            desc = desc[:197] + "..."
        amazon = field("Amazon") or ""
        if not amazon:
            am = re.search(r"https://www\.amazon\.com/[^\s|]+", block)
            amazon = am.group(0) if am else ""

        books.append(
            {
                "title": title,
                "authors": authors,
                "publisher": publisher,
                "year": published.split()[0] if published else published,
                "isbn": isbn,
                "themes": themes,
                "sentence": desc,
                "url": amazon,
            }
        )
    return books


def filter_substrate_md(text: str) -> str:
    """Keep headers, tables, code fences, and list lines with URLs or structured markers."""
    out: list[str] = []
    in_fence = False
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        if not s:
            if out and out[-1] != "":
                out.append("")
            continue
        if s.startswith("#"):
            if s.startswith("## The Story") or s.startswith("## Executive"):
                continue
            out.append(line)
            continue
        if s.startswith("|"):
            out.append(line)
            continue
        if s.startswith("- ") and (
            "http" in s
            or "ISBN" in s
            or s.startswith("- **")
            or re.search(r"\d{4}", s)
        ):
            out.append(line)
            continue
        if s.startswith("**") and ("http" in s or "|" in s):
            out.append(line)
            continue
    return "\n".join(out).strip()


def section_from_file(path: str, start: str | None = None, end: str | None = None) -> str:
    text = read(path)
    if start:
        idx = text.find(start)
        if idx >= 0:
            text = text[idx:]
    if end:
        idx = text.find(end)
        if idx >= 0:
            text = text[:idx]
    return filter_substrate_md(text)


def main() -> None:
    rubric = read("hirsch-affinity-rubric.md")
    ranked = read("hirsch-affinity-ranked-list.md")
    books_md = read("content/books.md")
    books = extract_books_table(books_md)

    bib_rows = []
    for b in books:
        bib_rows.append(
            f"| {b['title']} | {b['authors']} | {b['publisher']} | {b['year']} | {b['isbn']} | {b['themes']} | {b['sentence']} | {b['url']} |"
        )

    collab_json_nodes = re.search(
        r"\*\*Nodes\*\*.*?\n```json\n(.*?)\n```", read("network/collaborators.md"), re.S
    )
    collab_json_edges = re.search(
        r"\*\*Edges\*\*.*?\n```json\n(.*?)\n```", read("network/collaborators.md"), re.S
    )
    nodes = collab_json_nodes.group(1).strip() if collab_json_nodes else "[]"
    edges = collab_json_edges.group(1).strip() if collab_json_edges else "[]"

    parts: list[str] = [
        "# Alan Hirsch — Movement Leader Research (Substrate)",
        "",
        "**Slug:** `alan-hirsch`",
        "**Version:** 2.0.0 (substrate)",
        "**Last updated:** 2026-05-21",
        "**Purpose:** Machine-readable corpus for identity resolution, relational traversal, conceptual indexing, and voice fidelity. Not a consulting report.",
        "",
        "---",
        "",
        "## Identity",
        "",
        "| Field | Value | Source |",
        "|-------|-------|--------|",
        "| Full legal name | Alan Hirsch | [alanhirsch.org/about](https://www.alanhirsch.org/about), [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| Known as | Alan Hirsch; informal \"Al\" | *Untamed* introduction |",
        "| Born | 1959-10-24 | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch), [Prabook](https://prabook.com/web/alan.hirsch/3754228) |",
        "| Birthplace | Johannesburg, South Africa | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| Childhood | Cape Town, South Africa (from 1963) | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| Current location | Los Angeles area, United States (Thousand Oaks, CA per LinkedIn) | [IVP](https://www.ivpress.com/alan-hirsch), [LinkedIn](https://linkedin.com/in/alan-hirsch-98055b4) |",
        "| Nationality | Australian (emigrated 1983 from South Africa) | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "| Heritage | Jewish South African (non-observant; formative) | *Untamed*; profile research |",
        "| Primary roles | Author, missiologist, movement catalyst, speaker | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "| Primary organizations | 100Movements (100M); 5Q Collective | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "| US sponsor | Church Resource Ministries (CRM) | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "| Spouse / partner | Debra (Deb) Hirsch — co-author, Forge co-founder | *Untamed*; network research |",
        "| Education | Business & Marketing (Cape Town, ~1981–1983); Australian College of Theology (theology, 1989) | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch), *Untamed* |",
        "| Coined term | \"movemental\" (platform namesake) | committed-voice.md; org research |",
        "",
        "---",
        "",
        "## Disambiguation",
        "",
        "Four public figures named Alan Hirsch — **subject is #1 only**.",
        "",
        "| # | Identity | Disambiguate with | Exclude |",
        "|---|----------|-------------------|---------|",
        "| 1 | **Alan Hirsch (b. 1959)** — Australian missiologist, Forge / 100Movements / APEST | missional church, Forgotten Ways, 5Q, Forge | — |",
        "| 2 | Alan Hirsch — South African economist (MIGRA / NSI, Maastricht) | migration governance, NSI | missional, Forge |",
        "| 3 | Alan T. Hirsch, MD (1954–2017) — vascular medicine (UMN / Colorado) | vascular, deceased 2017 | missional, church |",
        "| 4 | Alan R. Hirsch, MD — smell & taste research (Chicago) | Smell & Taste Treatment Foundation | missional, church |",
        "",
        "**Reliable modifiers:** missional church, Forge, 100Movements, APEST, The Forgotten Ways, 5Q — combined with exclusion of cancer/vascular/smell/NSI/Maastricht.",
        "",
        "---",
        "",
        "## Editorial bio",
        "",
        read("committed-voice.md").split("## Editorial bio", 1)[1].strip().split("\n---", 1)[0].strip(),
        "",
        "---",
        "",
        "## Timeline",
        "",
        "| Year(s) | Milestone | Organization / work | Source |",
        "|---------|-----------|---------------------|--------|",
        "| 1959 | Born | Johannesburg, South Africa | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| 1963 | Relocated | Cape Town | [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| ~1977–1979 | Military service (mandatory, South Africa) | SA military | *Untamed* |",
        "| ~1979–1983 | University | Cape Town (business/marketing) | *Untamed*, [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| ~age 20 | Conversion to Christianity | During military service | *Untamed* |",
        "| 1983 | Emigrated to Australia | With Debra Hirsch | *Untamed* |",
        "| 1989 | Theology degree | Australian College of Theology | Voice guide / profile |",
        "| 1989–2004 | Senior pastor | South Melbourne Restoration Community (Churches of Christ) | *Untamed*, [Wikipedia](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| 1994 | Director of mission, education, development | Churches of Christ (Vic & Tas) | profile/identity.md |",
        "| 1996 | Co-founded Forge | Forge Mission Training Network (with Deb Hirsch, Michael Frost) | [Forge Global](https://www.forgeinternational.com/about) |",
        "| 2003 | Published | *The Shaping of Things to Come* (with Michael Frost) | content/books.md |",
        "| 2006 | Published | *The Forgotten Ways* (1st ed.) | content/books.md |",
        "| 2009 | Handbook; expanded Forge leadership | *Forgotten Ways Handbook*; Forge | profile/identity.md |",
        "| 2010 | Wheaton MA co-founder; adjunct roles | Wheaton, Fuller, Asbury, George Fox | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "| 2012 | *Permanent Revolution*; Future Travelers | Jossey-Bass; Future Travelers | content/books.md |",
        "| 2016 | 2nd ed. *Forgotten Ways*; founded 100M & 5Q Collective | Brazos; 100Movements | content/books.md |",
        "| 2017 | *5Q* | 100 Movements Publishing | content/books.md |",
        "| 2018–2023 | Interior-turn works | *Reframation*, *Metanoia* | analysis/content-analysis.md |",
        "| 2024 | *All Change* (with Rich Robinson) | 100 Movements Publishing | content/books.md |",
        "| Present | Founder/director | 100Movements, 5Q Collective; mentor NewThing; consultant Redeemer City to City | [alanhirsch.org/about](https://www.alanhirsch.org/about) |",
        "",
        "---",
        "",
        "## Frameworks",
        "",
        "### mDNA (Missional DNA) / Apostolic Genius",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2006 (*The Forgotten Ways*) |",
        "| Components | (1) Jesus is Lord [gates maturity], (2) disciple making, (3) missional-incarnational impulse, (4) apostolic environment (APEST), (5) organic systems, (6) liminality–communitas |",
        "| Visual / model | Six-element interdependent system; \"Apostolic Genius\" = latent movement potential when mDNA activates |",
        "| Adoption evidence | Seminal missional-church text; course adoptions (Wheaton MA, seminaries); 1,581+ Goodreads ratings on flagship; Chinese underground church & early-church cases cited |",
        "| Source | [The Forgotten Ways](https://www.amazon.com/Forgotten-Ways-Reactivating-Apostolic-Movements/dp/1587433869), [Baker 2nd ed.](https://bakerpublishinggroup.com/books/the-forgotten-ways-2nd-edition/2679716) |",
        "",
        "Hirsch argues every church carries dormant movement DNA recoverable through six interdependent practices; Christological maturity caps the whole system.",
        "",
        "### APEST / 5Q",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2012 (*Permanent Revolution*); scaled 2017 (*5Q*) |",
        "| Components | Apostle, Prophet, Evangelist, Shepherd, Teacher (Ephesians 4:11) as distributed callings and \"original intelligence\" of the Body |",
        "| Visual / model | Fivefold typology; 5Q assessments; team-design diagnostics |",
        "| Adoption evidence | **150,000+** assessments (5Q Central); Exponential pre-conferences; denominational training (e.g. LMC Anabaptist) |",
        "| Source | [5Q](https://www.amazon.com/5Q-Reactivating-Original-Intelligence-Capacity/dp/0998639303), [5qcentral.com](https://5qcentral.com) |",
        "",
        "Western churches are structurally Shepherd–Teacher heavy; recovering APE functions is presented as essential for movement health.",
        "",
        "### Christology → Missiology → Ecclesiology",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2008/2009 (*ReJesus*); runs through corpus |",
        "| Components | Christology determines missiology determines ecclesiology (ordering principle) |",
        "| Adoption evidence | Core argument of *ReJesus*; cited in missional ecclesiology discussions |",
        "| Source | *ReJesus* (100 Movements revised 2022) |",
        "",
        "Church form follows mission; mission follows from who Jesus is — distort Christology and downstream ecclesiology fails.",
        "",
        "### Incarnational mission",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2003 (*Shaping of Things to Come* with Frost) |",
        "| Components | Mission as embedded presence (6 P's in network: presence, proximity, prevenience, passion, powerlessness, proclamation) |",
        "| Adoption evidence | Foundational missional-incarnational pairing in global missional literature |",
        "| Source | [Shaping revised](https://www.amazon.com/Shaping-Things-Come-Innovation-21st-Century/dp/0801014913) |",
        "",
        "### Metanoia",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2023 (*Metanoia* with Rob Kelly) |",
        "| Components | Repentance as radical paradigm shift; personal, ecclesial, organizational change |",
        "| Adoption evidence | 2023 Awakenings / Missio Alliance launch; org-change audience |",
        "| Source | [Metanoia](https://www.amazon.com/Metanoia-Radically-Transforms-Churches-Organizations/dp/1955142378) |",
        "",
        "### Reframation",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | 2019 (*ReFramation* with Mark Nelson) |",
        "| Components | Re-enchanting mental frames for God, people, mission; arts, philosophy, Scripture |",
        "| Adoption evidence | Foreword Danielle Strickland; 100 Movements Publishing |",
        "| Source | [Reframation](https://www.amazon.com/Reframation-Seeing-Mission-Through-Reenchanted/dp/0998639338) |",
        "",
        "### Movemental vs. institutional thinking",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Introduced | Throughout corpus; organizational expression 100Movements |",
        "| Components | Organic, multiplicative, network structures vs. centralized maintenance; starfish/spider metaphor (*Starfish and the Spirit*, 2021) |",
        "| Adoption evidence | Future Travelers (megachurch transition); Exponential / Verge ecosystems |",
        "| Source | *On the Verge*, *Starfish and the Spirit*, [100movements.com](https://100movements.com) |",
        "",
        "---",
        "",
        "## Bibliography",
        "",
        "| Title | Author(s) | Publisher | Year | ISBN-13 | Key themes | One sentence | URL |",
        "|-------|-----------|-----------|------|---------|------------|--------------|-----|",
    ]
    parts.extend(bib_rows)
    parts.extend(
        [
        "",
        "**Summary:** 20 entries (16 unique titles); 5 solo, 15 co-authored; publishers 2003–2024 across 7 imprints; ~16,762 Goodreads ratings (92 editions). Sources: content/books.md, [Goodreads](https://www.goodreads.com/author/show/56757.Alan_Hirsch).",
        "",
        "### Theme map",
        "",
        "| Theme | Primary works |",
        "|-------|---------------|",
        "| mDNA / Apostolic Genius | *Forgotten Ways*, Handbook |",
        "| APEST / 5Q | *Permanent Revolution*, *5Q*, *Activating 5Q*, Playbook |",
        "| Incarnational mission | *Shaping of Things to Come*, *Right Here Right Now* |",
        "| Christology / ReJesus | *ReJesus* |",
        "| Communitas / liminality | *Faith of Leap* |",
        "| Metanoia / change | *Metanoia* |",
        "| Reframation / imagination | *Reframation* |",
        "| Megachurch → movement | *On the Verge*, Future Travelers |",
        "| Decentralized org | *Starfish and the Spirit* |",
        "",
        "### Content analysis (structured)",
        "",
        section_from_file(
            "analysis/content-analysis.md",
            "## Content Themes",
            "## Movemental Content Strategy",
        ),
        "",
        "### Recommended reading order",
        "",
        "| Order | Work | Rationale |",
        "|-------|------|-----------|",
        "| 1 | *The Forgotten Ways* (2nd ed., 2016) | Master mDNA framework |",
        "| 2 | *ReJesus* (rev. 2022) | Christological governor |",
        "| 3 | *5Q* (2017) | Scaled APEST |",
        "| 4 | *Shaping of Things to Come* (rev. 2013) | Incarnational foundation |",
        "| 5 | *Metanoia* (2023) | Interior transformation |",
        "| 6 | *Reframation* (2019) | Worldview re-enchantment |",
        "| 7 | *Permanent Revolution* (2012) | Deep APEST theory |",
        "| 8 | *Untamed* (2010) | Missional discipleship |",
        "| 9 | *Right Here, Right Now* (2011) | Accessible practitioner entry |",
        "| 10 | *All Change* (2024) | Current disruption application |",
        "",
        "---",
        "",
        "## Voice fingerprint",
        "",
        "### Five voice markers (weights for coherence score)",
        "",
        "| Marker | Target | Weight |",
        "|--------|--------|--------|",
        "| Christocentric anchoring | ≥ 0.7 | 30% |",
        "| Prophetic intensity | 0.5–0.8 | 25% |",
        "| Pastoral warmth | ≥ 0.5 | 20% |",
        "| Narrative imagery | ≥ 0.5 (2–5 metaphors / 100 words) | 15% |",
        "| Theological depth | ≥ 0.4 | 10% |",
        "| **Coherence target** | ≥ 0.75 | — |",
        "",
        "### Hallmark lexicon (9+ terms per substantial piece)",
        "",
        "mDNA, APEST, Apostolic Genius, communitas, liminality, missional, apostolic, movement, organic, fractal, Jesus is Lord, 5Q, metanoia, reframation, missional-incarnational, the forgotten ways, deep change, movemental",
        "",
        "### Antithesis prohibition (non-negotiable)",
        "",
        "Do **not** use contrastive negation→affirmation patterns: \"not X but Y\", \"rather than X\", \"instead of X\", \"far from X\", \"X, not Y\". Use direct affirmative, integrative language (\"and\", additive phrasing). Source: ALAN_HIRSCH_TIMELINE.md; profile/voice-analysis.md.",
        "",
        "### Representative quotes",
        "",
        "> \"Phenomenal Jesus movements grow precisely because they do not have centralized institutions to block growth through control.\" — *The Forgotten Ways*",
        "",
        "> \"Christology determines missiology, and missiology determines ecclesiology. Get this sequence wrong, and everything else gets distorted.\" — *ReJesus* (paraphrased core line)",
        "",
        "> \"For me, coming to Jesus was coming home in every way… the defining moment of my life.\" — *Untamed*, Introduction",
        "",
        "> \"The book you are holding is a plea to the church to reawaken the dormant potential within it.\" — *The Forgotten Ways*",
        "",
        "> \"The forms of archetypes… were evident in society long before the earthly ministry of Jesus… APEST brings enhanced, distinct meanings in the Jesus movement.\" — *5Q*, Introduction",
        "",
        "---",
        "",
        "## Theological positioning",
        "",
        "| Domain | Position |",
        "|--------|----------|",
        "| Tradition | Missional-incarnational; Churches of Christ (Australia) roots; cross-denominational practice |",
        "| Ecclesiology | Church as movement, not institution; organic systems |",
        "| Missiology | Sent, incarnational, everyday mission for all believers |",
        "| Leadership | Full APEST distributed in Body; Shepherd–Teacher imbalance critiqued |",
        "| Christology | Jesus is Lord gates mDNA; Hebraic over Hellenistic dualism |",
        "| Anthropology / formation | Communitas via liminality; disciple-making over information |",
        "| Culture | Post-Christendom; Western church in mission field |",
        "",
        "### Distinctive claims",
        "",
        "- APEST callings latent in **all** believers, not leadership offices only.",
        "- Apostolic, prophetic, evangelistic functions \"exiled\" in Western church.",
        "- \"Jesus is Lord\" maturity **caps** entire mDNA system performance.",
        "- Institutional preservation ≠ apostolic norm; multiplication over maintenance.",
        "- Every believer a missionary in sphere of influence.",
        "- Organic, reproducible patterns preferred over complex centralized management.",
        "",
        "---",
        "",
        "## Intellectual genealogy",
        "",
        "### Upstream influences",
        "",
        "| Person | Ideas adopted | Source |",
        "|--------|---------------|--------|",
        "| Lesslie Newbigin | Missio Dei, post-Christendom, church as sign/instrument | profile/theology.md |",
        "| Roland Allen | Indigenous church, Spirit-led expansion | profile/theology.md |",
        "| Dietrich Bonhoeffer | Costly discipleship, religionless Christianity | profile/theology.md |",
        "| Victor Turner | Liminality, communitas (anthropology → theology) | profile/theology.md |",
        "| Howard Snyder | Renewal movements, wineskins | profile/theology.md |",
        "| David Bosch | Transforming Mission paradigm | network/collaborators.md |",
        "| C.S. Lewis / Buber / von Balthasar | Imagination, I–Thou (*Reframation*) | network/collaborators.md |",
        "| Chinese house church / early church | Apostolic Genius case studies | *Forgotten Ways* |",
        "",
        "### Downstream impact (documented)",
        "",
        "| Channel | Evidence |",
        "|---------|----------|",
        "| APEST assessments | 150,000+ completions (5Q Central) |",
        "| Publishing vocabulary | mDNA, 5Q, movemental, Apostolic Genius in missional literature |",
        "| Seminary programs | Wheaton MA Missional Church Movements (co-founder) |",
        "| Denominations / networks | Exponential, Forge, Missio Alliance, organic church stream |",
        "| Citations | *Forgotten Ways* in missiology/ecclesiology; [Google Scholar profile](https://scholar.google.com/citations?user=ZqjYwf8AAAAJ&hl=en) |",
        "",
        "### Peer dialogue",
        "",
        "| Person | Relationship | Shared themes |",
        "|--------|--------------|---------------|",
        "| Michael Frost | Co-author (3 books); Forge co-founder | Incarnational mission, Christocentric ecclesiology |",
        "| Tim Catchim | Co-author (2 books) | APEST, apostolic practice |",
        "| Dave Ferguson | Co-author; Exponential | Megachurch → apostolic movement |",
        "| Ed Stetzer | Foreword; Missional Manifesto | Missional ecclesiology, research |",
        "| Neil Cole | Endorser; organic church | Movement multiplication |",
        "| Reggie McNeal | Peer | Missional leadership |",
        "| Darrell L. Guder | Foreword (*Permanent Revolution*) | Missio Dei, missional church |",
        "",
        "### Constructive tensions (documented)",
        "",
        "| Counterparty | Topic | Hirsch position | Source |",
        "|-------------|-------|-----------------|--------|",
        "| Reformed / Patheos critics | APEST for all believers | Full fivefold in Body | [Patheos critique](https://www.patheos.com/blogs/reintegrate/2017/04/21/caring-critique-alan-hirschs-apest-paradigm-churches/) |",
        "| Institutional defenders | Anti-institutional tone | Rebalance APE vs maintenance | [Reformed Journal](https://reformedjournal.com/bringing-balance-to-the-missional-church-movement/) |",
        "| Conservative critics | Gospel explicitness | Incarnational presence as proclamation | [Pulpit & Pen](https://pulpitandpen.org/2016/08/15/cautions-about-alan-hirsch/) |",
        "",
        "### Comparable authors (reach / genre, not affinity scores)",
        "",
        "| Author | Overlap |",
        "|--------|---------|",
        "| Michael Frost | Closest collaborator; shared audience |",
        "| Neil Cole | Organic church |",
        "| Reggie McNeal | Missional leadership |",
        "| Dave Ferguson | Multiplication / Exponential |",
        "| Brad Brisco | Forge; neighborhood mission |",
        "",
        "---",
        "",
        "## Network graph",
        "",
        "### Co-authors",
        "",
        "| Person | Joint works | Edge weight | Notes |",
        "|--------|-------------|-------------|-------|",
        "| Michael Frost | 3 | 9 | *Shaping*, *ReJesus*, *Faith of Leap* |",
        "| Tim Catchim | 2 | 7 | *Permanent Revolution*, Playbook |",
        "| Debra Hirsch | 1 | 8 | *Untamed*; Forge co-founder |",
        "| Lance Ford | 2 | 6 | *Right Here Right Now*, *Starfish and the Spirit* |",
        "| Dave Ferguson | 1 | 5 | *On the Verge* |",
        "| Mark Nelson | 1 | 5 | *Reframation* |",
        "| Jessie Cruickshank | 1 | 5 | *Activating 5Q* |",
        "| Rob Wegner | 1 | 4 | *Starfish* (3-way) |",
        "| Rob Kelly | 1 | 4 | *Metanoia* |",
        "| Darryn Altclass | 1 | 3 | *Forgotten Ways Handbook* |",
        "| Rich Robinson | 1 | 6 | *All Change*; MLC |",
        "",
        "### Endorsements received (sample)",
        "",
        "| From | For | Year | URL / note |",
        "|------|-----|------|------------|",
        "| Leonard Sweet | *Forgotten Ways* (1st ed.) | 2006 | Foreword |",
        "| Ed Stetzer | *Forgotten Ways* (2nd ed.) | 2016 | Foreword |",
        "| Darrell L. Guder | *Permanent Revolution* | 2012 | Foreword |",
        "| Jeff Vanderstelt | *Forgotten Ways* (2nd ed.) | 2016 | Afterword |",
        "| Neil Cole | *Forgotten Ways* (updated) | 2016 | Endorsement |",
        "| Danielle Strickland | *Activating 5Q* | 2018 | Endorsement |",
        "",
        "### Organizational affiliations",
        "",
        section_from_file("network/organizations.md", "## Organizations Founded", "## Organizations"),
        "",
        "### Endorsements (tables)",
        "",
        section_from_file("network/endorsements.md", "## Endorsements Received", "## Movemental Network"),
        "",
        "### Co-authors (detail)",
        "",
        section_from_file("network/collaborators.md", "## Co-Authors", "## Frequent Collaborators"),
        "",
        "### JSON graph (nodes)",
        "",
        "```json",
        nodes,
        "```",
        "",
        "### JSON graph (edges)",
        "",
        "```json",
        edges,
        "```",
        "",
        "---",
        "",
        "## Hirsch affinity rubric",
        "",
        rubric.strip(),
        "",
        "---",
        "",
        "## Hirsch affinity ranked list (500)",
        "",
        ranked.strip(),
        "",
        "---",
        "",
        "### Comparable authors (reach)",
        "",
        section_from_file("analysis/audience-analysis.md", "## Comparable Authors", "## Content Performance"),
        "",
        "## Reach metrics",
        "",
        "| Signal | Value | Date | Source |",
        "|--------|-------|------|--------|",
        "| APEST / 5Q assessments | 150,000+ | 2026-03 | [5qcentral.com](https://5qcentral.com) |",
        "| Twitter/X followers | ~37,900 | 2026-03 | digital-presence/social-media.md |",
        "| Facebook (combined) | ~20,800 | 2026-03 | digital-presence/social-media.md |",
        "| Substack subscribers | ~1,500 | 2026-03 | [alanhirsch1.substack.com](https://alanhirsch1.substack.com) |",
        "| Goodreads ratings (all editions) | 16,762 | 2026-03 | [Goodreads](https://www.goodreads.com/author/show/56757.Alan_Hirsch) |",
        "| Goodreads editions | 92 | 2026-03 | Goodreads |",
        "| Books in print | 20 (16 unique) | 2026-03 | content/books.md |",
        "| Publishers | 7 | 2026-03 | content/books.md |",
        "| Flagship Goodreads avg | 4.08 (*Forgotten Ways*) | 2026-03 | media/reviews.md |",
        "| Podcast guest appearances | 28+ on 22+ shows | 2026-03 | fragmentation-story.md |",
        "| Hosted podcast | 5QCast (~30 eps.) | 2026-03 | fragmentation-story.md |",
        "| Videos (third-party channels) | 38+ on 20+ channels | 2026-03 | content/videos.md |",
        "| Personal YouTube channel | None | 2026-03 | fragmentation-story.md |",
        "| Audiobooks on Audible | 3 of 20 confirmed | 2026-03 | fragmentation-story.md |",
        "| Conference audience (cumulative est.) | 50,000+ | 2026-03 | network/events.md |",
        "| Exponential (typical) | 5,000+ / event | 2026-03 | network/events.md |",
        "| Wikipedia | Yes | — | [en.wikipedia.org/wiki/Alan_Hirsch](https://en.wikipedia.org/wiki/Alan_Hirsch) |",
        "| Google Scholar profile | Yes | — | [scholar.google.com/citations?user=ZqjYwf8AAAAJ](https://scholar.google.com/citations?user=ZqjYwf8AAAAJ&hl=en) |",
        "",
        "---",
        "",
        "## Distribution inventory",
        "",
        "Structured catalogue of where content lives (no marketing narrative). Sources: fragmentation-story.md, digital-presence/*, content/*.",
        "",
        "### Books",
        "",
        "| Count | Detail |",
        "|-------|--------|",
        "| 20 titles | 16 unique works + revised editions |",
        "| Publishers | 100 Movements (9), Baker/Brazos (7), Hendrickson (2), Zondervan (2), Jossey-Bass (1), Exponential (1), Missio (1) |",
        "| Years | 2003–2024 |",
        "| Retail surfaces | Amazon, Goodreads, IVP, Baker, Audible, Christianbook, Everand, OverDrive, Google Books |",
        "| Audiobooks (confirmed) | *Reframation*, *Untamed*, *On the Verge*, *Starfish*, *All Change* (+ partial set) |",
        "| Gap | Flagship *Forgotten Ways*, *5Q*, *Shaping*, *ReJesus*, *Faith of Leap* — no Audible at research date |",
        "",
        "### Articles & blogs",
        "",
        "| Platform | Count / notes | URL |",
        "|----------|---------------|-----|",
        "| Saturate | 11-part series + posts | https://saturatetheworld.com/author/ahirsch/ |",
        "| alanhirsch.org/blog | Irregular archive | https://www.alanhirsch.org/blog |",
        "| Substack | ~1,500 subs; irregular | https://alanhirsch1.substack.com |",
        "| Verge Network | Articles + video tag | https://vergenetwork.org/tag/alan-hirsch/ |",
        "| Missional Church Network | Category archive | https://www.missionalchurchnetwork.com/blog/category/Alan+Hirsch |",
        "| Exponential | Contributor profile | https://exponential.org/person/alan-hirsch/ |",
        "",
        "### Audio",
        "",
        "| Type | Count | Notes |",
        "|------|-------|-------|",
        "| Guest podcast episodes | 28+ | 22+ feeds (Everyday Disciple, Exponential, ChurchLeaders, etc.) |",
        "| Hosted | 5QCast | Only owned show |",
        "",
        "### Video",
        "",
        "| Type | Count | Notes |",
        "|------|-------|-------|",
        "| Clips on third-party channels | 38+ | Verge, Exponential, ChurchLeaders, Morling, Asbury, etc. |",
        "| Owned YouTube | 0 | — |",
        "| Structured academic video | Morling *Missiology To Go* (6 sessions) | https://info.morling.edu.au/missiology-to-go-fivefold-leadership |",
        "",
        "### Courses & assessments",
        "",
        "| Asset | URL |",
        "|-------|-----|",
        "| APEST / Forgotten Ways assessments | https://theforgottenways.org, https://apest.5qcentral.com |",
        "| Ephesiology masterclasses | https://masterclasses.ephesiology.com |",
        "| Forge Teachable residency | Forge platforms |",
        "| Wheaton MA | https://www.wheaton.edu/graduate-school/degrees/ma-in-missional-church-movements/ |",
        "",
        "### Websites & orgs",
        "",
        "| Site | Role |",
        "|------|------|",
        "| https://alanhirsch.org | Personal (Squarespace) |",
        "| https://100movements.com | Org / publishing |",
        "| https://5qcentral.com | APEST hub |",
        "| https://forgeinternational.com / forgeamerica.org | Forge |",
        "| https://movementleaderscollective.com | MLC |",
        "",
        "### Social",
        "",
        "| Platform | Handle / URL | Followers |",
        "|----------|--------------|-----------|",
        "| X/Twitter | @alanhirsch | ~37,900 |",
        "| Facebook | alanhirsch + secondary page | ~14,000 + ~6,800 |",
        "| LinkedIn | alan-hirsch-98055b4 | Active |",
        "| Instagram | @alandhirsch (unverified) | Minimal |",
        "| YouTube (personal) | — | — |",
        "| TikTok | — | — |",
        "",
        "### Academic / papers",
        "",
        "| Item | Status |",
        "|------|--------|",
        "| Personal Google Scholar | Exists; metrics thin in scrape |",
        "| Peer-reviewed journal articles (solo) | Not catalogued |",
        "| Lausanne co-authored paper (Bhojpuri) | Location unknown — open question |",
        "",
        "### Translations",
        "",
        "Spanish, Portuguese, German, French materials referenced in repo files; not fully catalogued on public platform URLs (open question).",
        "",
        "### Detailed catalogue (from fragmentation-story.md)",
        "",
        section_from_file(
            "fragmentation-story.md",
            "## Informational Fragmentation",
            "## Relational Fragmentation",
        ),
        "",
        "### Relational inventory (organizations & co-authors)",
        "",
        section_from_file(
            "fragmentation-story.md",
            "## Relational Fragmentation",
            "## Embodied / In Their Head",
        ),
        "",
        "### Content gap table (factual state only)",
        "",
        "| Format | Current state | Missing / thin |",
        "|--------|---------------|----------------|",
        "| Owned video hub | 0 channels | Centralized library |",
        "| Audiobooks | 3/20 | Major titles |",
        "| Email list | ~1.5K Substack vs ~38K social | Conversion gap |",
        "| Post-assessment journey | Score only | Documented onward path gap at theforgottenways.org |",
        "| Blog cadence | Irregular | — |",
        "",
        "### Gap inventory (factual tables only)",
        "",
        section_from_file(
            "analysis/gap-analysis.md",
            "## Content Format Gaps",
            "## Top Repurposing Opportunities",
        ),
        "",
        "---",
        "",
        "## Press coverage",
        "",
        section_from_file("media/press-coverage.md", "## Featured Coverage"),
        "",
        "---",
        "",
        "## Reviews",
        "",
        section_from_file("media/reviews.md", "## Review Summary by Book"),
        "",
        "### Editorial review tables",
        "",
        section_from_file("media/reviews.md", "## Detailed Reviews", "## Review Patterns"),
        "",
        "---",
        "",
        "## Citations & reference",
        "",
        section_from_file("media/citations.md", "## Google Scholar Profile", "## Awards & Recognition"),
        "",
        "---",
        "",
        "## Events",
        "",
        section_from_file("network/events.md", "## Upcoming Events", "## Speaking Topics"),
        "",
        "### Recurring events",
        "",
        section_from_file("network/events.md", "## Recurring Events", "## Event Type Distribution"),
        "",
        "### Geographic reach (tables)",
        "",
        section_from_file("network/events.md", "## Geographic Reach", "## Event Metrics"),
        "",
        "---",
        "",
        "## Sources (provenance)",
        "",
        "| URL | Verifies |",
        "|-----|----------|",
        "| https://www.alanhirsch.org/about | Identity, org roles |",
        "| https://en.wikipedia.org/wiki/Alan_Hirsch | Birth, career summary |",
        "| https://www.ivpress.com/alan-hirsch | Publisher bibliography |",
        "| https://www.goodreads.com/author/show/56757.Alan_Hirsch | Ratings, editions |",
        "| https://5qcentral.com | APEST scale, team |",
        "| https://www.forgeinternational.com/about | Forge founding |",
        "| https://scholar.google.com/citations?user=ZqjYwf8AAAAJ | Scholar profile |",
        "| https://bakerpublishinggroup.com/books/the-forgotten-ways-2nd-edition/2679716 | Flagship book metadata |",
        "",
        "### Reference URLs (from sources.md — no search logs)",
        "",
        section_from_file("sources.md", "## Sources Consulted", "## Research Gaps"),
        "",
        "### Digital presence files",
        "",
        section_from_file("digital-presence/websites.md", "## Owned"),
        "",
        section_from_file("digital-presence/social-media.md", "## Platform Summary"),
        "",
        section_from_file("content/articles.md", "## Articles"),
        "",
        section_from_file("content/videos.md", "## Video Inventory"),
        "",
        section_from_file("content/audio.md", "## Podcast"),
        "",
        section_from_file("content/courses.md", "## Courses"),
        "",
        "---",
        "",
        "## Open questions",
        "",
        "- Peer-reviewed journal articles authored solo — not catalogued.",
        "- Lausanne / Bhojpuri co-authored paper — location not captured.",
        "- Instagram handle @alandhirsch — needs verification.",
        "- Exact Google Scholar citation counts / h-index — profile exists; metrics not scraped.",
        "- Free eBooks on alanhirsch.org/ebooks — titles and gating mechanism not itemized.",
        "- WorldCat / library holdings — not measured.",
        "- Speaking fee range — unknown.",
        "- Full translation inventory on live platforms vs. repo files.",
        "",
        ]
    )

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    line_count = len(parts)
    print(f"Wrote {OUT} ({OUT.read_text().count(chr(10))} lines)")


if __name__ == "__main__":
    main()
