export type HomeHeroAudienceTab = "leaders" | "nonprofits" | "churches" | "institutions";

/**
 * Same-origin iframe sources (generated by `pnpm sync:hero-previews`).
 * `leaders` is vendored from `docs/templates/alan-hirsch/pages/` when present; otherwise
 * `scripts/sync-hero-previews.ts` copies `docs/templates/alan-hirsch/exemplars/exemplar-landing-general.html`
 * to `leaders/index.html` so builds keep working.
 * Other audiences use `docs/templates/audience-previews/*.html` when present; otherwise a stub is written.
 */
export const HOME_HERO_PREVIEW_URLS: Record<HomeHeroAudienceTab, string> = {
  leaders: "/hero-previews/leaders/index.html",
  nonprofits: "/hero-previews/nonprofits/index.html",
  churches: "/hero-previews/churches/index.html",
  institutions: "/hero-previews/institutions/index.html",
};

export const HOME_HERO_PREVIEW_TITLES: Record<HomeHeroAudienceTab, string> = {
  leaders: "Alan Hirsch app shell — static pages (docs/templates/alan-hirsch/pages)",
  nonprofits: "Nonprofit mission system homepage preview",
  churches: "Church formation system homepage preview",
  institutions: "Institutional intelligence homepage preview",
};
